### ISSUE TITLE
Cannot store/access iCloud keychain passwords

### ISSUE THREAD

**Issue by hmijail** [jfitzell/mozilla-keychain#82]
After enabling debug logging, I am seeing this in the Browser Console:
nsLoginManager:Counting logins matching host: "http://www.maxipizza.pl" formSubmitURL:  httpRealm: null nsLoginManager.js:405
Login storage:_searchLogins: returning 0 logins storage-json.js:409
Login storage:_countLogins: counted logins: 0
Keychain: -> countLogins('http://www.maxipizza.pl','',null)
Keychain:   scheme:http host:www.maxipizza.pl port:null
Keychain: Using default keychain search list
Keychain:   Items found: 0
Keychain: No items found. Checking mozilla storage...

I don't see anything in /var/log/system.log as admin, nor in Console.app's "all messages" as non-admin.

Keychain Access shows that I have 2 passwords stored (both in keychain iCloud), and Safari sure does use them.

I don't know if earlier Firefox or OS X versions did work well, I just came back to Firefox recently after some longish time in Safari.

**Comment by jfitzell** [comment]
If you store passwords with Firefox do those work? Unfortunately Apple does not allow applications to access the iCloud/Local Items keychain unless they are compiled/signed with appropriate permissions set. Mozilla, unfortunately, have no interest in doing this because they don't support Keychain, so you can currently only access passwords stored in other keychains (usually your "login" keychain, though you can create new ones yourself).

So Firefox

**Comment by jfitzell** [comment]
If you store passwords with Firefox do those work? Unfortunately Apple does not allow applications to access the iCloud/Local Items keychain unless they are compiled/signed with appropriate permissions set. Mozilla, unfortunately, have no interest in doing this because they don't support Keychain, so you can currently only access passwords stored in other keychains (usually your "login" keychain, though you can create new ones yourself..

So Firefox

**Comment by hmijail** [comment]
Yes, when a password is stored in Firefox, it shows in the keychain and does work back in Firefox. 

A couple of ideas: would it be possible to have a  signed helper binary which would interface with the keychain without restriction and which would send the passwords to Firefox? How difficult or insecure would be that?
Or, would it be possible for a user to sign his own Firefox?

**Comment by jfitzell** [comment]
Hmm... I did look at that. As I recall, applications also have to be distributed and signed by the App Store to access iCloud (another reason Mozilla isn't interested, I guess). So while a helper app would presumably be technically possible, it would be a pain to install and I'd be a bit surprised if Apple approved it in the store. I think the same restriction may have prevented self-signing, though maybe there's some way to do it for "development builds" or something... I eventually gave up.

Between that, all the changes Mozilla keep making to their password storage, and their refusal to deal with Keychain at all, I'm beginning to feel like this extension's days may be numbered. I'm holding on and trying to fix things as they break for now, but avoiding putting extra effort into it at this point...

**Comment by RichieB2B** [comment]
How is Google Chrome dealing with this issue? I can't see them taking the Mac App Store route either.

**Comment by jfitzell** [comment]
Does Chrome access your iCloud passwords? I think they have the same challenge: https://discussions.apple.com/message/28115283#28115283

**Comment by RichieB2B** [comment]
From that discussion it seems Chrome indeed has the same issue. It could be my memory, but IIRC I used to be able to share passwords between Safari and Firefox using this addon. Those passwords were also synced between devices (both OS X and iOS). Now I have two separate sets of stored passwords: Safari (iCloud keychain) and Firefox (login keychain). Is only the iCloud keychain synced between devices? If so, what it the practical use of this addon today?

**Comment by jfitzell** [comment]
I can't quite remember... there may have been a time where Apple didn't restrict access to the iCloud keychain as strongly as it does now. There was definitely a release of OS X where things changed, but I don't recall whether it was the original introduction of iCloud keychain sync or a later release.

Currently:
* Safari always stores passwords in the iCloud (or Local Items) keychain
* This extension stores passwords into your default keychain (the one that is bold in Keychain Access) by default. You can change your default keychain in Keychain Access or can configure this extension to store passwords in a different keychain. None of this will give you access to the iCloud keychain from Firefox, however.
* Only the iCloud keychain is synced with other Apple devices
* Both Safari and Firefox should *read* passwords from all other keychains

Personally, it's not a big deal for me: I use Firefox as my main browser, using Safari only occasionally; and I don't use iCloud Keychain sync. So Safari can read my Firefox passwords on the occasions where that is necessary and I periodically take a look at my Local Items keychain, moving any passwords created there into my login keychain.

Apple has definitely made interoperability between browsers worse here. Even without multiple browsers, though, I would still use the Keychain because I would rather my passwords were encrypted in one place by the operating system rather than encrypted by Mozilla in my Firefox profile. But obviously your needs may be different.
